/*
 * Netlify's API documentation
 *
 * Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.  This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://www.netlify.com/docs/api/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).  Additionally, we have two API clients for your convenience: - [Go Client](https://github.com/netlify/open-api#go-client) - [JS Client](https://github.com/netlify/js-client)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountType {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<serde_json::Value>,
    #[serde(rename = "monthly_dollar_price", skip_serializing_if = "Option::is_none")]
    pub monthly_dollar_price: Option<i32>,
    #[serde(rename = "yearly_dollar_price", skip_serializing_if = "Option::is_none")]
    pub yearly_dollar_price: Option<i32>,
    #[serde(rename = "monthly_seats_addon_dollar_price", skip_serializing_if = "Option::is_none")]
    pub monthly_seats_addon_dollar_price: Option<i32>,
    #[serde(rename = "yearly_seats_addon_dollar_price", skip_serializing_if = "Option::is_none")]
    pub yearly_seats_addon_dollar_price: Option<i32>,
}

impl AccountType {
    pub fn new() -> AccountType {
        AccountType {
            id: None,
            name: None,
            description: None,
            capabilities: None,
            monthly_dollar_price: None,
            yearly_dollar_price: None,
            monthly_seats_addon_dollar_price: None,
            yearly_seats_addon_dollar_price: None,
        }
    }
}


